namespace R5.Core.Entidades;

/// <summary>País ISO 3166 (tabla interna del canon R3, clase Paises de Entidades.vb):
/// valida los códigos de país de trazabilidad en recepción y resuelve el país
/// numérico del AI 7030 de las etiquetas GS1-128 de ternera.</summary>
public sealed record Pais(string Iso2, string Iso3, int Num, string Nombre);

public static class Paises
{
    /// <summary>Busca por código ISO2 (dos letras); null si no existe.</summary>
    public static Pais? PorIso2(string? iso2)
        => _lista.FirstOrDefault(p => p.Iso2.Equals(iso2?.Trim() ?? "", StringComparison.OrdinalIgnoreCase));

    /// <summary>Busca por código numérico ISO (p. ej. 724 = España); null si no existe.</summary>
    public static Pais? PorNumero(int num) => Array.Find(_lista, p => p.Num == num);

    private static readonly Pais[] _lista =
    {
        new("AD", "AND", 20, "Andorra"),
        new("AE", "ARE", 784, "Emiratos Árabes Unidos"),
        new("AF", "AFG", 4, "Afganistán"),
        new("AG", "ATG", 28, "Antigua y Barbuda"),
        new("AI", "AIA", 660, "Anguila"),
        new("AL", "ALB", 8, "Albania"),
        new("AM", "ARM", 51, "Armenia"),
        new("AN", "ANT", 530, "Antillas Neerlandesas"),
        new("AO", "AGO", 24, "Angola"),
        new("AQ", "ATA", 10, "Antártida"),
        new("AR", "ARG", 32, "Argentina"),
        new("AS", "ASM", 16, "Samoa Americana"),
        new("AT", "AUT", 40, "Austria"),
        new("AU", "AUS", 36, "Australia"),
        new("AW", "ABW", 533, "Aruba"),
        new("AX", "ALA", 248, "Islas Áland"),
        new("AZ", "AZE", 31, "Azerbaiyán"),
        new("BA", "BIH", 70, "Bosnia y Herzegovina"),
        new("BB", "BRB", 52, "Barbados"),
        new("BD", "BGD", 50, "Bangladesh"),
        new("BE", "BEL", 56, "Bélgica"),
        new("BF", "BFA", 854, "Burkina Faso"),
        new("BG", "BGR", 100, "Bulgaria"),
        new("BH", "BHR", 48, "Bahréin"),
        new("BI", "BDI", 108, "Burundi"),
        new("BJ", "BEN", 204, "Benin"),
        new("BL", "BLM", 652, "San Bartolomé"),
        new("BM", "BMU", 60, "Bermudas"),
        new("BN", "BRN", 96, "Brunéi"),
        new("BO", "BOL", 68, "Bolivia"),
        new("BR", "BRA", 76, "Brasil"),
        new("BS", "BHS", 44, "Bahamas"),
        new("BT", "BTN", 64, "Bhután"),
        new("BV", "BVT", 74, "Isla Bouvet"),
        new("BW", "BWA", 72, "Botsuana"),
        new("BY", "BLR", 112, "Belarús"),
        new("BZ", "BLZ", 84, "Belice"),
        new("CA", "CAN", 124, "Canadá"),
        new("CC", "CCK", 166, "Islas Cocos"),
        new("CF", "CAF", 140, "República Centro-Africana"),
        new("CG", "COG", 178, "Congo"),
        new("CH", "CHE", 756, "Suiza"),
        new("CI", "CIV", 384, "Costa de Marfil"),
        new("CK", "COK", 184, "Islas Cook"),
        new("CL", "CHL", 152, "Chile"),
        new("CM", "CMR", 120, "Camerún"),
        new("CN", "CHN", 156, "China"),
        new("CO", "COL", 170, "Colombia"),
        new("CR", "CRI", 188, "Costa Rica"),
        new("CU", "CUB", 192, "Cuba"),
        new("CV", "CPV", 132, "Cabo Verde"),
        new("CX", "CXR", 162, "Islas Christmas"),
        new("CY", "CYP", 196, "Chipre"),
        new("CZ", "CZE", 203, "República Checa"),
        new("DE", "DEU", 276, "Alemania"),
        new("DJ", "DJI", 262, "Yibuti"),
        new("DK", "DNK", 208, "Dinamarca"),
        new("DM", "DMA", 212, "Domínica"),
        new("DO", "DOM", 214, "República Dominicana"),
        new("DZ", "DZA", 12, "Argel"),
        new("EC", "ECU", 218, "Ecuador"),
        new("EE", "EST", 233, "Estonia"),
        new("EG", "EGY", 818, "Egipto"),
        new("EH", "ESH", 732, "Sahara Occidental"),
        new("ER", "ERI", 232, "Eritrea"),
        new("ES", "ESP", 724, "España"),
        new("ET", "ETH", 231, "Etiopía"),
        new("FI", "FIN", 246, "Finlandia"),
        new("FJ", "FJI", 242, "Fiji"),
        new("FK", "KLK", 238, "Islas Malvinas"),
        new("FM", "FSM", 583, "Micronesia"),
        new("FO", "FRO", 234, "Islas Faroe"),
        new("FR", "FRA", 250, "Francia"),
        new("GA", "GAB", 266, "Gabón"),
        new("GB", "GBR", 826, "Reino Unido"),
        new("GD", "GRD", 308, "Granada"),
        new("GE", "GEO", 268, "Georgia"),
        new("GF", "GUF", 254, "Guayana Francesa"),
        new("GG", "GGY", 831, "Guernsey"),
        new("GH", "GHA", 288, "Ghana"),
        new("GI", "GIB", 292, "Gibraltar"),
        new("GL", "GRL", 304, "Groenlandia"),
        new("GM", "GMB", 270, "Gambia"),
        new("GN", "GIN", 324, "Guinea"),
        new("GP", "GLP", 312, "Guadalupe"),
        new("GQ", "GNQ", 226, "Guinea Ecuatorial"),
        new("GR", "GRC", 300, "Grecia"),
        new("GS", "SGS", 239, "Georgia del Sur e Islas Sandwich del Sur"),
        new("GT", "GTM", 320, "Guatemala"),
        new("GU", "GUM", 316, "Guam"),
        new("GW", "GNB", 624, "Guinea-Bissau"),
        new("GY", "GUY", 328, "Guayana"),
        new("HK", "HKG", 344, "Hong Kong"),
        new("HM", "HMD", 334, "Islas Heard y McDonald"),
        new("HN", "HND", 340, "Honduras"),
        new("HR", "HRV", 191, "Croacia"),
        new("HT", "HTI", 332, "Haití"),
        new("HU", "HUN", 348, "Hungría"),
        new("ID", "IDN", 360, "Indonesia"),
        new("IE", "IRL", 372, "Irlanda"),
        new("IL", "ISR", 376, "Israel"),
        new("IM", "IMN", 833, "Isla de Man"),
        new("IN", "IND", 356, "India"),
        new("IO", "IOT", 86, "Territorio Británico del Océano Índico"),
        new("IQ", "IRQ", 368, "Irak"),
        new("IR", "IRN", 364, "Irán"),
        new("IS", "ISL", 352, "Islandia"),
        new("IT", "ITA", 380, "Italia"),
        new("JE", "JEY", 832, "Jersey"),
        new("JM", "JAM", 388, "Jamaica"),
        new("JO", "JOR", 400, "Jordania"),
        new("JP", "JPN", 392, "Japón"),
        new("KE", "KEN", 404, "Kenia"),
        new("KG", "KGZ", 417, "Kirguistán"),
        new("KH", "KHM", 116, "Camboya"),
        new("KI", "KIR", 296, "Kiribati"),
        new("KM", "COM", 174, "Comoros"),
        new("KN", "KNA", 659, "San Cristóbal y Nieves"),
        new("KP", "PRK", 408, "Corea del Norte"),
        new("KR", "KOR", 410, "Corea del Sur"),
        new("KW", "KWT", 414, "Kuwait"),
        new("KY", "CYM", 136, "Islas Caimán"),
        new("KZ", "KAZ", 398, "Kazajstán"),
        new("LA", "LAO", 418, "Laos"),
        new("LB", "LBN", 422, "Líbano"),
        new("LC", "LCA", 662, "Santa Lucía"),
        new("LI", "LIE", 438, "Liechtenstein"),
        new("LK", "LKA", 144, "Sri Lanka"),
        new("LR", "LBR", 430, "Liberia"),
        new("LS", "LSO", 426, "Lesotho"),
        new("LT", "LTU", 440, "Lituania"),
        new("LU", "LUX", 442, "Luxemburgo"),
        new("LV", "LVA", 428, "Letonia"),
        new("LY", "LBY", 434, "Libia"),
        new("MA", "MAR", 504, "Marruecos"),
        new("MC", "MCO", 492, "Mónaco"),
        new("MD", "MDA", 498, "Moldova"),
        new("ME", "MNE", 499, "Montenegro"),
        new("MG", "MDG", 450, "Madagascar"),
        new("MH", "MHL", 584, "Islas Marshall"),
        new("MK", "MKD", 807, "Macedonia"),
        new("ML", "MLI", 466, "Mali"),
        new("MM", "MMR", 104, "Myanmar"),
        new("MN", "MNG", 496, "Mongolia"),
        new("MO", "MAC", 446, "Macao"),
        new("MQ", "MTQ", 474, "Martinica"),
        new("MR", "MRT", 478, "Mauritania"),
        new("MS", "MSR", 500, "Montserrat"),
        new("MT", "MLT", 470, "Malta"),
        new("MU", "MUS", 480, "Mauricio"),
        new("MV", "MDV", 462, "Maldivas"),
        new("MW", "MWI", 454, "Malawi"),
        new("MX", "MEX", 484, "México"),
        new("MY", "MYS", 458, "Malasia"),
        new("MZ", "MOZ", 508, "Mozambique"),
        new("NA", "NAM", 516, "Namibia"),
        new("NC", "NCL", 540, "Nueva Caledonia"),
        new("NE", "NER", 562, "Níger"),
        new("NF", "NFK", 574, "Islas Norkfolk"),
        new("NG", "NGA", 566, "Nigeria"),
        new("NI", "NIC", 558, "Nicaragua"),
        new("NL", "NLD", 528, "Países Bajos"),
        new("NO", "NOR", 578, "Noruega"),
        new("NP", "NPL", 524, "Nepal"),
        new("NR", "NRU", 520, "Nauru"),
        new("NU", "NIU", 570, "Niue"),
        new("NZ", "NZL", 554, "Nueva Zelanda"),
        new("OM", "OMN", 512, "Omán"),
        new("PA", "PAN", 591, "Panamá"),
        new("PE", "PER", 604, "Perú"),
        new("PF", "PYF", 258, "Polinesia Francesa"),
        new("PG", "PNG", 598, "Papúa Nueva Guinea"),
        new("PH", "PHL", 608, "Filipinas"),
        new("PK", "PAK", 586, "Pakistán"),
        new("PL", "POL", 616, "Polonia"),
        new("PM", "SPM", 666, "San Pedro y Miquelón"),
        new("PN", "PCN", 612, "Islas Pitcairn"),
        new("PR", "PRI", 630, "Puerto Rico"),
        new("PS", "PSE", 275, "Palestina"),
        new("PT", "PRT", 620, "Portugal"),
        new("PW", "PLW", 585, "Islas Palaos"),
        new("PY", "PRY", 600, "Paraguay"),
        new("QA", "QAT", 634, "Qatar"),
        new("RE", "REU", 638, "Reunión"),
        new("RO", "ROU", 642, "Rumanía"),
        new("RS", "SRB", 688, "Serbia y Montenegro"),
        new("RU", "RUS", 643, "Rusia"),
        new("RW", "RWA", 646, "Ruanda"),
        new("SA", "SAU", 682, "Arabia Saudita"),
        new("SB", "SLB", 90, "Islas Solomón"),
        new("SC", "SYC", 690, "Seychelles"),
        new("SD", "SDN", 736, "Sudán"),
        new("SE", "SWE", 752, "Suecia"),
        new("SG", "SGP", 702, "Singapur"),
        new("SH", "SHN", 654, "Santa Elena"),
        new("SI", "SVN", 705, "Eslovenia"),
        new("SJ", "SJM", 744, "Islas Svalbard y Jan Mayen"),
        new("SK", "SVK", 703, "Eslovaquia"),
        new("SL", "SLE", 694, "Sierra Leona"),
        new("SM", "SMR", 674, "San Marino"),
        new("SN", "SEN", 686, "Senegal"),
        new("SO", "SOM", 706, "Somalia"),
        new("SR", "SUR", 740, "Surinam"),
        new("ST", "STP", 678, "Santo Tomé y Príncipe"),
        new("SV", "SLV", 222, "El Salvador"),
        new("SY", "SYR", 760, "Siria"),
        new("SZ", "SWZ", 748, "Suazilandia"),
        new("TC", "TCA", 796, "Islas Turcas y Caicos"),
        new("TD", "TCD", 148, "Chad"),
        new("TF", "ATF", 260, "Territorios Australes Franceses"),
        new("TG", "TGO", 768, "Togo"),
        new("TH", "THA", 764, "Tailandia"),
        new("TJ", "TJK", 762, "Tayikistán"),
        new("TK", "TKL", 772, "Tokelau"),
        new("TL", "TLS", 626, "Timor-Leste"),
        new("TM", "TKM", 795, "Turkmenistán"),
        new("TN", "TUN", 788, "Túnez"),
        new("TO", "TON", 776, "Tonga"),
        new("TR", "TUR", 792, "Turquía"),
        new("TT", "TTO", 780, "Trinidad y Tobago"),
        new("TV", "TUV", 798, "Tuvalu"),
        new("TW", "TWN", 158, "Taiwán"),
        new("TH", "TZA", 834, "Tanzania"),
        new("UA", "UKR", 804, "Ucrania"),
        new("UG", "UGA", 800, "Uganda"),
        new("US", "USA", 840, "Estados Unidos de América"),
        new("UY", "URY", 858, "Uruguay"),
        new("UZ", "UZB", 860, "Uzbekistán"),
        new("VA", "VAT", 336, "Ciudad del Vaticano"),
        new("VC", "VCT", 670, "San Vicente y las Granadinas"),
        new("VE", "VEN", 862, "Venezuela"),
        new("VG", "VGB", 92, "Islas Vírgenes Británicas"),
        new("VI", "VIR", 850, "Islas Vírgenes de los Estados Unidos de América"),
        new("VN", "VNM", 704, "Vietnam"),
        new("VU", "VUT", 548, "Vanuatu"),
        new("WF", "WLF", 876, "Wallis y Futuna"),
        new("WS", "WSM", 882, "Samoa"),
        new("YE", "YEM", 887, "Yemen"),
        new("YT", "MYT", 175, "Mayotte"),
        new("ZA", "ZAF", 710, "Sudáfrica"),
    };
}
